# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
before_install:
  - R -e 'source("https://install-github.me/r-lib/remotes")'
  - cd fireNASA
addons:
  apt:
    packages:
      - libudunits2-dev

os:
    - linux

r:
    - 3.4